name: Generate HTML File Listing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate HTML file listing
        run: |
          # Create a Python script to generate the index.html file
          echo "
import os

# Define the directory containing your data files
data_directory = 'data'
output_file = 'index.html'

# Start building the HTML content
html_content = '<html><head><title>File Listing</title></head><body>'
html_content += '<h1>File Listing</h1><ul>'

# Loop through each file in the directory
for root, _, files in os.walk(data_directory):
    for file in files:
        file_path = os.path.join(root, file)
        file_url = f'https://dharsourabh.github.io/cricgonzo/{file_path.replace(os.sep, '/')}'
        
        # Add each file as a link in the HTML file
        html_content += f'<li><a href=\"{file_url}\">{file}</a></li>'

html_content += '</ul></body></html>'

# Write the HTML content to the index.html file
with open(output_file, 'w') as f:
    f.write(html_content)
          " > generate_index.py

          # Run the Python script to generate the index.html file
          python generate_index.py

      - name: Verify index.html creation
        run: |
          if [ -f "index.html" ]; then
            echo "index.html successfully created."
            cat index.html  # Optional: Output the HTML content for debugging
          else
            echo "index.html was not created."
            exit 1  # Exit with an error if index.html does not exist
          fi

      - name: Commit and push changes
        if: success()  # Only attempt to commit if previous steps succeeded
        run: |
          git config --global user.name "Dharsourabh"
          git config --global user.email "dharsourabh@gmail.com"
          
          git add index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of index.html with file listing"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
