name: Sync Cricsheet Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download Cricsheet data
        run: |
          # Create a temporary directory for new data
          mkdir -p new_data
          cd new_data
          curl -L -O https://cricsheet.org/downloads/all_csv2.zip  # Update URL if needed
          unzip -o all_csv2.zip
          rm all_csv2.zip
          cd ..

      - name: Compare with existing data and update if necessary
        id: compare-outcome
        run: |
          mkdir -p data  # Ensure data directory exists
          
          # Check for new or changed files and copy them over
          CHANGES=false
          for file in new_data/*; do
            if ! cmp -s "$file" "data/$(basename "$file")"; then
              cp "$file" "data/"
              echo "Updated $(basename "$file")"
              CHANGES=true
            fi
          done

          # Check if any changes were detected
          if [ "$CHANGES" = false ]; then
            echo "No new or updated files found."
            echo "changed=false" >> $GITHUB_ENV
            exit 0
          else
            echo "Changes detected. Preparing to commit."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data/
          git commit -m "Automated update of Cricsheet data with new or updated files"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
