name: Sync Cricsheet Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download Cricsheet data
        run: |
          # Create temporary directory for the downloaded data
          mkdir -p new_data
          cd new_data
          curl -L -O https://cricsheet.org/downloads/all_csv2.zip  # Use the correct URL for the data type you want
          unzip -o all_csv2.zip
          rm all_csv2.zip
          cd ..

      - name: Separate and merge files
        run: |
          # Ensure data directory exists
          mkdir -p data

          # Initialize merged files
          echo "Initializing merged files"
          echo "Match Details File" > data/merged_match_details.csv
          echo "Ball by Ball Data" > data/merged_ball_by_ball.csv

          # Loop through each downloaded file and merge accordingly
          for file in new_data/*.csv; do
            filename=$(basename "$file")
            if [[ "$filename" == *"info"* ]]; then
              echo "Merging $filename as match details"
              tail -n +2 "$file" >> data/merged_match_details.csv
            else
              echo "Merging $filename as ball-by-ball data"
              tail -n +2 "$file" >> data/merged_ball_by_ball.csv
            fi
          done

      - name: Check for changes
        run: |
          # Check if the merged files differ from the previous version
          if ! git diff --quiet data/merged_match_details.csv || ! git diff --quiet data/merged_ball_by_ball.csv; then
            echo "Changes detected in merged files."
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_ENV
            exit 0
          fi

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config --global user.name "Dharsourabh"
          git config --global user.email "dharsourabh@gmail.com"
          
          git add data/merged_match_details.csv data/merged_ball_by_ball.csv
          git commit -m "Automated update of merged Cricsheet 2 files data"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
